// ============================================================
//  AHB Lite — Cover Properties (Part 3)
//  Project  : EE-5214 AMBA AHB-Lite RAM Verification
//  Role     : B — Assertions & Formal
//  Spec     : ARM IHI0033A
//
//  Purpose  : Confirm interesting corner cases are reachable
//             under the given assumptions.
//             If a scenario is unreachable, explain why
//             in the Part 3 report.
//
//  Required by project spec (Part 3 Task 3.2):
//  COV1 — HREADY=0 held for 3+ consecutive cycles
//  COV2 — WRAP4 burst where wrap actually happens
//  COV3 — Write immediately followed by read same address
//  COV4 — HRESP=ERROR generated by slave
//  COV5 — Back-to-back NONSEQ with no IDLE
//
//  Additional corner cases:
//  COV6  — BUSY inserted inside burst
//  COV7  — INCR burst at 1KB boundary edge
//  COV8  — Byte write to each byte lane
//  COV9  — Half-word write to each half-word lane
//  COV10 — Reset asserted mid-transaction
//  COV11 — Full INCR4 burst write then readback
//  COV12 — Full WRAP4 burst with actual wrap
//  COV13 — Back-to-back writes same address
//  COV14 — Read after reset (first transaction)
//  COV15 — HREADY=0 during burst (wait state in burst)
// ============================================================

import ahb3lite_pkg::*;

module ahb_cover #(
    parameter int HADDR_SIZE = 32,
    parameter int HDATA_SIZE = 32
)(
    input                       HRESETn,
    input                       HCLK,
    input                       HSEL,
    input      [HADDR_SIZE-1:0] HADDR,
    input      [HDATA_SIZE-1:0] HWDATA,
    input      [HDATA_SIZE-1:0] HRDATA,
    input                       HWRITE,
    input      [           2:0] HSIZE,
    input      [           2:0] HBURST,
    input      [           1:0] HTRANS,
    input                       HREADYOUT,
    input                       HREADY,
    input                       HRESP
);

    // ---- default clocking --------------------------------------
    default clocking ahb_clk @(posedge HCLK); endclocking
    default disable iff (!HRESETn);

    // ============================================================
    //  REQUIRED COVER PROPERTIES (Project Spec Part 3)
    // ============================================================

    // COV1 — HREADY=0 held for 3+ consecutive cycles
    //        Confirms slave can insert multiple wait states
    cov_hready_low_3cycles: cover property (
        HSEL && !HREADYOUT ##1
             !HREADYOUT ##1
             !HREADYOUT ##1
              HREADYOUT
    );

    // COV2 — WRAP4 burst where wrap actually happens
    //        Address must actually wrap at boundary
    //        (not just increment — must see address go backward)
    cov_wrap4_actual_wrap: cover property (
        HSEL && HBURST == HBURST_WRAP4 &&
        HTRANS == HTRANS_SEQ && HREADY &&
        HSIZE == HSIZE_B32 &&
        // address wrapped back: current < previous
        HADDR < $past(HADDR)
    );

    // COV3 — Write immediately followed by read to same address
    //        No IDLE between — back-to-back pipelined
    cov_write_then_read_same_addr: cover property (
        HSEL && HTRANS == HTRANS_NONSEQ &&
        HWRITE == 1'b1 && HREADY ##1
        HSEL && HTRANS == HTRANS_NONSEQ &&
        HWRITE == 1'b0 && HREADY &&
        HADDR == $past(HADDR)
    );

    // COV4 — HRESP=ERROR generated by slave
    //        Confirms error response path is reachable
    cov_hresp_error: cover property (
        HSEL && HRESP == HRESP_ERROR &&
        HREADYOUT == 1'b0 ##1
        HRESP == HRESP_ERROR &&
        HREADYOUT == 1'b1
    );

    // COV5 — Back-to-back NONSEQ with no IDLE between
    //        Two separate single transfers consecutively
    cov_back2back_nonseq: cover property (
        HSEL && HTRANS == HTRANS_NONSEQ && HREADY ##1
        HSEL && HTRANS == HTRANS_NONSEQ && HREADY
    );

    // ============================================================
    //  ADDITIONAL CORNER CASES
    // ============================================================

    // COV6 — BUSY inserted inside INCR burst
    //        Master pauses mid-burst with BUSY
    cov_busy_in_incr_burst: cover property (
        HSEL && HBURST == HBURST_INCR &&
        HTRANS == HTRANS_NONSEQ && HREADY ##1
        HTRANS == HTRANS_SEQ    && HREADY ##1
        HTRANS == HTRANS_BUSY   && HREADY ##1
        HTRANS == HTRANS_SEQ    && HREADY
    );

    // COV7 — INCR burst approaching 1KB boundary edge
    //        Address bits [9:0] near max before boundary
    cov_incr_near_1kb: cover property (
        HSEL && HBURST == HBURST_INCR &&
        HTRANS inside {HTRANS_NONSEQ, HTRANS_SEQ} &&
        HREADY && HADDR[9:0] > 10'h3E0
    );

    // COV8 — Byte write to each byte lane
    cov_byte_write_lane0: cover property (
        HSEL && HTRANS == HTRANS_NONSEQ && HREADY &&
        HSIZE == HSIZE_B8 && HWRITE == 1'b1 &&
        HADDR[1:0] == 2'b00
    );

    cov_byte_write_lane1: cover property (
        HSEL && HTRANS == HTRANS_NONSEQ && HREADY &&
        HSIZE == HSIZE_B8 && HWRITE == 1'b1 &&
        HADDR[1:0] == 2'b01
    );

    cov_byte_write_lane2: cover property (
        HSEL && HTRANS == HTRANS_NONSEQ && HREADY &&
        HSIZE == HSIZE_B8 && HWRITE == 1'b1 &&
        HADDR[1:0] == 2'b10
    );

    cov_byte_write_lane3: cover property (
        HSEL && HTRANS == HTRANS_NONSEQ && HREADY &&
        HSIZE == HSIZE_B8 && HWRITE == 1'b1 &&
        HADDR[1:0] == 2'b11
    );

    // COV9 — Half-word write to each lane
    cov_hword_write_low: cover property (
        HSEL && HTRANS == HTRANS_NONSEQ && HREADY &&
        HSIZE == HSIZE_B16 && HWRITE == 1'b1 &&
        HADDR[1] == 1'b0
    );

    cov_hword_write_high: cover property (
        HSEL && HTRANS == HTRANS_NONSEQ && HREADY &&
        HSIZE == HSIZE_B16 && HWRITE == 1'b1 &&
        HADDR[1] == 1'b1
    );

    // COV10 — Reset asserted mid-transaction
    //         HRESETn goes low while SEQ transfer in progress
    cov_reset_mid_transaction: cover property (
        @(posedge HCLK)
        HSEL && HTRANS == HTRANS_SEQ && HREADY ##1
        !HRESETn
    );

    // COV11 — Full INCR4 write burst then readback
    //         4 writes followed by 4 reads same addresses
    cov_incr4_write_burst: cover property (
        HSEL && HBURST == HBURST_INCR4 &&
        HTRANS == HTRANS_NONSEQ && HWRITE == 1'b1 && HREADY ##1
        HTRANS == HTRANS_SEQ    && HWRITE == 1'b1 && HREADY ##1
        HTRANS == HTRANS_SEQ    && HWRITE == 1'b1 && HREADY ##1
        HTRANS == HTRANS_SEQ    && HWRITE == 1'b1 && HREADY ##1
        HTRANS == HTRANS_IDLE
    );

    // COV12 — Full WRAP4 burst all 4 beats including wrap
    cov_wrap4_full_burst: cover property (
        HSEL && HBURST == HBURST_WRAP4 &&
        HTRANS == HTRANS_NONSEQ && HREADY ##1
        HTRANS == HTRANS_SEQ    && HREADY ##1
        HTRANS == HTRANS_SEQ    && HREADY ##1
        HTRANS == HTRANS_SEQ    && HREADY ##1
        HTRANS == HTRANS_IDLE
    );

    // COV13 — Back-to-back writes to same address
    //         Second write overwrites first
    cov_back2back_writes_same_addr: cover property (
        HSEL && HTRANS == HTRANS_NONSEQ &&
        HWRITE == 1'b1 && HREADY ##1
        HSEL && HTRANS == HTRANS_NONSEQ &&
        HWRITE == 1'b1 && HREADY &&
        HADDR == $past(HADDR) &&
        HWDATA != $past(HWDATA)
    );

    // COV14 — First read after reset
    //         Confirms DUT responds correctly after reset
    cov_first_read_after_reset: cover property (
        @(posedge HCLK)
        $rose(HRESETn) ##[1:8]
        (HSEL && HTRANS == HTRANS_NONSEQ &&
         HWRITE == 1'b0 && HREADY &&
         HRESP == HRESP_OKAY)
    );

    // COV15 — Wait state inserted during burst
    //         HREADYOUT goes low during SEQ beat
    cov_wait_state_in_burst: cover property (
        HSEL && HBURST == HBURST_INCR4 &&
        HTRANS == HTRANS_NONSEQ && HREADY ##1
        HTRANS == HTRANS_SEQ    && !HREADYOUT ##1
        HTRANS == HTRANS_SEQ    && HREADYOUT
    );

    // COV16 — WRAP8 burst with actual wrap
    cov_wrap8_actual_wrap: cover property (
        HSEL && HBURST == HBURST_WRAP8 &&
        HTRANS == HTRANS_SEQ && HREADY &&
        HSIZE == HSIZE_B32 &&
        HADDR < $past(HADDR)
    );

    // COV17 — Single byte read after byte write
    //         Confirms byte lane read correctness
    cov_byte_write_then_read: cover property (
        HSEL && HTRANS == HTRANS_NONSEQ &&
        HSIZE == HSIZE_B8 && HWRITE == 1'b1 && HREADY ##1
        HSEL && HTRANS == HTRANS_NONSEQ &&
        HSIZE == HSIZE_B8 && HWRITE == 1'b0 && HREADY &&
        HADDR == $past(HADDR)
    );

    // COV18 — Word write then byte read same address
    //         Tests partial read after full write
    cov_word_write_byte_read: cover property (
        HSEL && HTRANS == HTRANS_NONSEQ &&
        HSIZE == HSIZE_B32 && HWRITE == 1'b1 && HREADY ##1
        HSEL && HTRANS == HTRANS_NONSEQ &&
        HSIZE == HSIZE_B8  && HWRITE == 1'b0 && HREADY &&
        HADDR[HADDR_SIZE-1:2] == $past(HADDR[HADDR_SIZE-1:2])
    );

endmodule